
scene.insert(nil,'skybox','skybox',{ texture = "nebula_px.jpg, nebula_nx.jpg, nebula_pz.jpg, nebula_nz.jpg, nebula_py.jpg, nebula_ny.jpg" })
scene.position('skybox',0,0,0)
scene.angle('skybox',0,0,0)
scene.scale('skybox',1,1,1)
scene.visible('skybox',true)
scene.material('skybox',-1,{roughness=0.8,metalness=0.1,color='#fff'})

scene.insert(nil,'planet','earth',{ texture = "earth.jpg", textureNight = "earth_night.jpg", radius = 500, slices = 128 })
scene.position('earth',0,0,0)
scene.angle('earth',0,-0.52,1.57)
scene.scale('earth',1,1,1)
scene.visible('earth',true)
scene.material('earth',-1,{roughness=0.8,metalness=0.1,color='#fff'})

scene.insert(nil,'geometry','moon',{shape='sphere',texture='moon.jpg',r=50,slices=128})
scene.position('moon',0,800,0)
scene.angle('moon',0,0,0)
scene.scale('moon',1,1,1)
scene.visible('moon',true)
scene.material('moon',-1,{roughness=0.8,metalness=0.1,color='#fff'})

scene.insert(nil,'static','friendship',{ meshFile="frienship7.3ds"})
scene.position('friendship',0,0,0)
scene.angle('friendship',0,0,0)
scene.scale('friendship',1,1,1)
scene.visible('friendship',true)
scene.material('friendship',-1,{roughness=0.05,metalness=0.13,color='#3AF5FFFF'})

scene.insert('friendship','particles','flame1',{ texture = "smoke.tga", size = 1.1, count = 100, spread = 2.5, dz = -23, fade = 8, color = 0xEFB59DFF, dark = false })
scene.position('flame1',-0.48,0.18,1.2)
scene.angle('flame1',0,0,0)
scene.scale('flame1',1,1,1)
scene.visible('flame1',true)
scene.material('flame1',-1,{roughness=0.8,metalness=0.1,color='#fff'})

scene.insert('friendship','particles','flame2',{ texture = "smoke.tga", size = 1.1, count = 100, spread = 2.5, dz = -23, fade = 8, color = 0xEFB59DFF, dark = false })
scene.position('flame2',-0.66,-1.38,1.2)
scene.angle('flame2',0,0,0)
scene.scale('flame2',1,1,1)
scene.visible('flame2',true)
scene.material('flame2',-1,{roughness=0.8,metalness=0.1,color='#fff'})

scene.insert('friendship','particles','flame3',{ texture = "smoke.tga", size = 1.1, count = 100, spread = 2.5, dz = -23, fade = 8, color = 0xEFB59DFF, dark = false })
scene.position('flame3',0.69,-0.66,1.2)
scene.angle('flame3',0,0,0)
scene.scale('flame3',1,1,1)
scene.visible('flame3',true)
scene.material('flame3',-1,{roughness=0.8,metalness=0.1,color='#fff'})

