scene.insert(nil, "skybox", "skybox", { texture = "sky.jpg, sky.jpg, sky.jpg, sky.jpg, sky_up.jpg, sky_down.jpg" })
scene.insert(nil, "cloud", "cloud", { skyColor = "#2265B3FF", cloudColor = "#CCCCCCFF", cloudSize = 20 })
scene.insert(nil, "animation", "jiuniang", { meshFile = "jiuniang/jiuniang.ms3d" })
scene.insert("jiuniang", "sound", "enen", { soundFile = "sound/enen.mp3" })
scene.insert("jiuniang", "text", "tips", { text = "zyn", fontSize = 16 })
scene.insert(nil, "geometry", "sphere2", { shape = "sphere", r = 5.0, texture = "mars.jpg" })
scene.insert(nil, "geometry", "sphere3", { shape = "sphere", r = 0.5, texture = "mars.jpg" })
scene.insert(nil, "geometry", "cylinder", { shape = "cylinder", r = 1.0, h = 1.0, texture = "brick.jpg" })
scene.insert("cylinder", "static", "head", { meshFile = "head/head.obj" })
scene.insert(nil, "geometry", "torus", { shape = "torus", r = 8.0, c = 1.0, texture = "brick.jpg" })
scene.insert(nil, "geometry", "cone", { shape = "cone", r = 1.0, h = 1.0, texture = "brick.jpg" })
scene.insert(nil, "billboard", "billboard", { texture = "brick.jpg", width = 5, height = 5 })
scene.insert(nil, "flame", "flame", { texture = "flame/fire_diffuse.png", distortionMap = "flame/fire_distortion.png", alphaMask = "flame/fire_opacity.png" })
scene.insert(nil, "terrain", "terrain", { heightScale = 30, mapScale = 1000, heightMap = "height.bmp", texture = "sand.jpg, ground.jpg, grass.jpg, rock.jpg", blendMap = "blend.png" })
scene.insert(nil, "geometry", "cube", { shape = "box", texture = "brick.jpg" })
scene.insert("cube", "geometry", "cube_up", { shape = "box", texture = "brick.jpg" })
scene.insert("cube", "geometry", "cube_down", { shape = "box", texture = "brick.jpg" })
scene.insert("cube", "geometry", "cube_front", { shape = "box", texture = "brick.jpg" })
scene.insert("cube", "geometry", "cube_back", { shape = "box", texture = "brick.jpg" })
scene.insert("cube", "geometry", "cube_right", { shape = "box", texture = "brick.jpg" })
scene.insert("cube", "geometry", "cube_left", { shape = "box", texture = "brick.jpg" })
scene.insert("cube", "geometry", "cube_left_front_up", { shape = "box", texture = "brick.jpg" })
scene.insert("cube", "geometry", "cube_right_front_up", { shape = "box", texture = "brick.jpg" })
scene.insert("cube", "geometry", "cube_right_back_up", { shape = "box", texture = "brick.jpg" })
scene.insert("cube", "geometry", "cube_left_back_up", { shape = "box", texture = "brick.jpg" })
scene.insert("cube", "geometry", "cube_left_front_down", { shape = "box", texture = "brick.jpg" })
scene.insert("cube", "geometry", "cube_right_front_down", { shape = "box", texture = "brick.jpg" })
scene.insert("cube", "geometry", "cube_right_back_down", { shape = "box", texture = "brick.jpg" })
scene.insert("cube", "geometry", "cube_left_back_down", { shape = "box", texture = "brick.jpg" })
scene.insert("cube", "geometry", "cube_left_up", { shape = "box", texture = "brick.jpg" })
scene.insert("cube", "geometry", "cube_front_up", { shape = "box", texture = "brick.jpg" })
scene.insert("cube", "geometry", "cube_right_up", { shape = "box", texture = "brick.jpg" })
scene.insert("cube", "geometry", "cube_back_up", { shape = "box", texture = "brick.jpg" })
scene.insert("cube", "geometry", "cube_left_down", { shape = "box", texture = "brick.jpg" })
scene.insert("cube", "geometry", "cube_front_down", { shape = "box", texture = "brick.jpg" })
scene.insert("cube", "geometry", "cube_right_down", { shape = "box", texture = "brick.jpg" })
scene.insert("cube", "geometry", "cube_back_down", { shape = "box", texture = "brick.jpg" })
scene.insert("cube", "geometry", "cube_left_front", { shape = "box", texture = "brick.jpg" })
scene.insert("cube", "geometry", "cube_right_front", { shape = "box", texture = "brick.jpg" })
scene.insert("cube", "geometry", "cube_right_back", { shape = "box", texture = "brick.jpg" })
scene.insert("cube", "geometry", "cube_left_back", { shape = "box", texture = "brick.jpg" })
scene.insert(nil, "geometry", "cube_ground", { shape = "box", x = 1000, y = 1000, z = 0.1, texture = "transparent" })
scene.insert(nil, "board", "board", { texture = "brick.jpg", width = 5, height = 1.4 })
scene.insert(nil, "particles", "particles", { texture = "smoke.tga", size = 0.5, count = 100 })
scene.insert(nil, "fresnel", "bubble1", { meshFile = "ball.3ds" })
scene.insert(nil, "fresnel", "bubble2", { meshFile = "ball.3ds" })
scene.insert(nil, "water", "water", { normalMap = "water.jpg", depth = -0.5 })
scene.insert(nil, "lensflare", "lensflare")
scene.insert(nil, "axis", "axis")
scene.insert(nil, "line", "line", { color = "red", width = 2.0 })
--scene.insert(nil, "screen", "screen", { texture = "grass.jpg", width = 200, height = 200 })
--scene.insert(nil, "board", "camera", { texture = "camera:0", width = 4, height = 3 })
--scene.insert(nil, "board", "video", { texture = "video/01.mpg", width = 4, height = 3 })
--scene.insert(nil, "planet", "planet", { texture = "earth.jpg", textureNight = "earth_night.jpg", radius = 10, slices = 64 })

scene.position("terrain", 0, 0, 14)
scene.scale("jiuniang", 0.03, 0.03, 0.03)
scene.position("tips", 0, 70.0, 0)
scene.position("sphere2", 0, 10, 10)
scene.position("sphere3", 0, -3, 1)
scene.position("cylinder", 0, 0, 3)
scene.scale("head", 0.01, 0.01, 0.01)
scene.angle("head", 3.14159, 0, 0)
scene.position("head", 0, 0, 1.5)
scene.position("torus", 0, 0, 0.5)
scene.position("billboard", -10, 10, 2)
scene.position("flame", 0, 0, -0.3)
scene.position("cube", 0, 4, 1)
scene.position("cube_up", 0, 0, 1.1)
scene.position("cube_down", 0, 0, -1.1)
scene.position("cube_front", 0, 1.1, 0)
scene.position("cube_back", 0, -1.1, 0)
scene.position("cube_right", 1.1, 0, 0)
scene.position("cube_left", -1.1, 0, 0)
scene.position("cube_left_front_up", -1.1, -1.1, 1.1)
scene.position("cube_right_front_up", 1.1, -1.1, 1.1)
scene.position("cube_right_back_up", 1.1, 1.1, 1.1)
scene.position("cube_left_back_up", -1.1, 1.1, 1.1)
scene.position("cube_left_front_down", -1.1, -1.1, -1.1)
scene.position("cube_right_front_down", 1.1, -1.1, -1.1)
scene.position("cube_right_back_down", 1.1, 1.1, -1.1)
scene.position("cube_left_back_down", -1.1, 1.1, -1.1)
scene.position("cube_left_up", -1.1, 0, 1.1)
scene.position("cube_front_up", 0, -1.1, 1.1)
scene.position("cube_right_up", 1.1, 0, 1.1)
scene.position("cube_back_up", 0, 1.1, 1.1)
scene.position("cube_left_down",-1.1, 0, -1.1 )
scene.position("cube_front_down", 0, -1.1, -1.1)
scene.position("cube_right_down", 1.1, 0, -1.1)
scene.position("cube_back_down", 0, 1.1, -1.1)
scene.position("cube_left_front", -1.1, -1.1, 0)
scene.position("cube_right_front", 1.1, -1.1, 0)
scene.position("cube_right_back", 1.1, 1.1, 0)
scene.position("cube_left_back", -1.1, 1.1, 0)
scene.position("cube_ground", 0, 0, -0.8)
scene.position("board", 27, 35, 0.5)
scene.angle("board", 0, 0, 0.87)
scene.position("camera", -2, 2, 2)
scene.position("video", 2, 2, 2)
scene.position("planet", 0, 50, 20)
scene.position("bubble1", 10, 10, 2)
scene.position("bubble2", 10, 5, 2)
scene.position("particles", 0, 0, 6)

physics.bind("sphere2", { mass = 5.0, linearDamping = -0.1, angularDamping = -0.1, friction = 0.8, restitution = 0.9 })
physics.bind("sphere3", { mass = 0.5, linearDamping = -0.1, angularDamping = -0.1 })
physics.bind("torus", { mass = 0 })
physics.bind("cube", { mass = 0 })
physics.bind("cube_ground", { shape = "plane", mass = 0 })
physics.bind("cube_up", { mass = 0.5, linearDamping = -0.1, angularDamping = -0.1 })
physics.bind("cube_down", { mass = 0.5, linearDamping = -0.1, angularDamping = -0.1 })
physics.bind("cube_front", { mass = 0.5, linearDamping = -0.1, angularDamping = -0.1 })
physics.bind("cube_back", { mass = 0.5, linearDamping = -0.1, angularDamping = -0.1 })
physics.bind("cube_right", { mass = 0.5, linearDamping = -0.1, angularDamping = -0.1 })
physics.bind("cube_left", { mass = 0.5, linearDamping = -0.1, angularDamping = -0.1 })
physics.bind("cube_left_front_up", { mass = 0.5, linearDamping = -0.1, angularDamping = -0.1 })
physics.bind("cube_right_front_up", { mass = 0.5, linearDamping = -0.1, angularDamping = -0.1 })
physics.bind("cube_right_back_up", { mass = 0.5, linearDamping = -0.1, angularDamping = -0.1 })
physics.bind("cube_left_back_up", { mass = 0.5, linearDamping = -0.1, angularDamping = -0.1 })
physics.bind("cube_left_front_down", { mass = 0.5, linearDamping = -0.1, angularDamping = -0.1 })
physics.bind("cube_right_front_down", { mass = 0.5, linearDamping = -0.1, angularDamping = -0.1 })
physics.bind("cube_right_back_down", { mass = 0.5, linearDamping = -0.1, angularDamping = -0.1 })
physics.bind("cube_left_back_down", { mass = 0.5, linearDamping = -0.1, angularDamping = -0.1 })
physics.bind("cube_left_up", { mass = 0.5, linearDamping = -0.1, angularDamping = -0.1 })
physics.bind("cube_front_up", { mass = 0.5, linearDamping = -0.1, angularDamping = -0.1 })
physics.bind("cube_right_up", { mass = 0.5, linearDamping = -0.1, angularDamping = -0.1 })
physics.bind("cube_back_up", { mass = 0.5, linearDamping = -0.1, angularDamping = -0.1 })
physics.bind("cube_left_down", { mass = 0.5, linearDamping = -0.1, angularDamping = -0.1 })
physics.bind("cube_front_down", { mass = 0.5, linearDamping = -0.1, angularDamping = -0.1 })
physics.bind("cube_right_down", { mass = 0.5, linearDamping = -0.1, angularDamping = -0.1 })
physics.bind("cube_back_down", { mass = 0.5, linearDamping = -0.1, angularDamping = -0.1 })
physics.bind("cube_left_front", { mass = 0.5, linearDamping = -0.1, angularDamping = -0.1 })
physics.bind("cube_right_front", { mass = 0.5, linearDamping = -0.1, angularDamping = -0.1 })
physics.bind("cube_right_back", { mass = 0.5, linearDamping = -0.1, angularDamping = -0.1 })
physics.bind("cube_left_back", { mass = 0.5, linearDamping = -0.1, angularDamping = -0.1 })
physics.joint("jiuniang", "Bone15", 1.0, 200.0, 100.0, -0.01)
physics.joint("jiuniang", "Bone16", 1.0, 200.0, 100.0, -0.01)

scene.handle("jiuniang", "PointFacing", {joint='Bip01-Head', front_x=0, front_y=0, front_z=1, angle=0.785})