-- video_src = "/storage/sdcard1/pole dancing.mp4"

-- if gPlatform == "android" then
	-- scene.clear()
	-- camera.type("default")
	-- camera.fov(120)
	-- camera.position(0, 0, 0)
	-- scene.insert(nil, "board", "video", { texture = video_src, width = 2, height = 1 })
	-- scene.insert(nil, "geometry", "sphere", { shape = "sphere", r = 5, slices = 64, texture = video_src, reversed = true })
	-- scene.visible("video", false)
	-- graphics.pointLight(0, 0, 0, 1000)
	-- graphics.stereo(true)
	-- post.enable("oculus", true)
-- end