
scene.insert(nil,'geometry','ball',{shape='sphere',texture='football.jpg',r=1,slices=32,reversed=false})
scene.position('ball',0,-20,-3.4)
scene.angle('ball',0,0,0)
scene.scale('ball',1,1,1)
scene.visible('ball',true)
physics.bind('ball',{mass=1,shape='sphere',linearDamping=0,angularDamping=0,friction=0.5,restitution=0.3,trigger=false})
scene.material('ball',-1,{roughness=0,metalness=0,color='#059BFFFF'})

scene.insert(nil,'geometry','ban',{shape='box',texture='yellow',x=7,y=7,z=0.2,reversed=false})
scene.position('ban',0,0,7.2)
scene.angle('ban',1.570795,0,0)
scene.scale('ban',1,1,1)
scene.visible('ban',true)
physics.bind('ban',{mass=0,shape='box',linearDamping=0,angularDamping=0,friction=0.5,restitution=0.3,trigger=false})
scene.material('ban',-1,{roughness=0.41,metalness=0.7,color='#fff'})

scene.insert('ban','geometry','kuang',{shape='torus',texture='red',r=2,c=0.5,slices=32,reversed=false})
scene.position('kuang',0,-2.96,2)
scene.angle('kuang',-1.570795,0,0)
scene.scale('kuang',1,1,1)
scene.visible('kuang',true)
physics.bind('kuang',{mass=0,shape='torus',linearDamping=0,angularDamping=0,friction=0.5,restitution=0.3,trigger=false})
scene.material('kuang',-1,{roughness=0.6,metalness=0.19,color='#fff'})

scene.insert('kuang','geometry','detect',{shape='cylinder',texture='',r=1.5,h=0.5,slices=32,reversed=false})
scene.position('detect',0,0,-1.24)
scene.angle('detect',0,0,0)
scene.scale('detect',1,1,1)
scene.visible('detect',false)
physics.bind('detect',{mass=0,shape='cylinder',linearDamping=0,angularDamping=0,friction=0.5,restitution=0.3,trigger=true})
scene.material('detect',-1,{roughness=0.8,metalness=0.1,color='#fff'})

scene.insert(nil,'geometry','detect_ground',{shape='plane',texture='',w=50,h=20,reversed=false})
scene.position('detect_ground',0,0,-1)
scene.angle('detect_ground',0,0,0)
scene.scale('detect_ground',1,1,1)
scene.visible('detect_ground',false)
physics.bind('detect_ground',{mass=0,shape='plane',linearDamping=0,angularDamping=0,friction=0.5,restitution=0.3,trigger=true})
scene.material('detect_ground',-1,{roughness=0.8,metalness=0.1,color='#fff'})

scene.insert(nil,'animation','rabbit1',{meshFile='rabbit.glb',start=true,skeleton=false})
scene.position('rabbit1',-11,10,-13.2)
scene.angle('rabbit1',0,0,0)
scene.scale('rabbit1',1,1,1)
scene.visible('rabbit1',true)
scene.material('rabbit1',-1,{roughness=0.42,metalness=0.81,color='#fff'})

scene.insert(nil,'animation','rabbit2',{meshFile='rabbit.glb',start=true,skeleton=false})
scene.position('rabbit2',11,10,-13.2)
scene.angle('rabbit2',0,0,0)
scene.scale('rabbit2',1,1,1)
scene.visible('rabbit2',true)
scene.material('rabbit2',-1,{roughness=0.42,metalness=0.81,color='#fff'})

scene.insert(nil,'geometry','background',{shape='sphere',texture='green',r=50,slices=32,reversed=true})
scene.position('background',0,0,0)
scene.angle('background',0,0,0)
scene.scale('background',1,1,1)
scene.visible('background',true)
scene.material('background',-1,{roughness=0.8,metalness=0.1,color='#fff'})

scene.insert(nil,'water','water',{normalMap='water.jpg',depth=0})
scene.position('water',0,0,-13.06)
scene.angle('water',0,0,0)
scene.scale('water',1,1,1)
scene.visible('water',true)
scene.material('water',-1,{roughness=0.8,metalness=0.1,color='#fff'})

